from docx import Document
from pathlib import Path

base = Path('/mnt/data/janus_n13_claim_figure_revision')
out = Path('/mnt/data/janus_n15_targeted_revision')
out.mkdir(exist_ok=True)

main_in = base/'Janus_MoSSe_ThermalStationary_Manuscript_v3.docx'
si_in = base/'Janus_MoSSe_ThermalStationary_SI_v3.docx'
main_out = out/'Janus_MoSSe_RedTeamScoped_Manuscript_v4.docx'
si_out = out/'Janus_MoSSe_RedTeamScoped_SI_v4.docx'


def replace_exact(doc, old, new):
    hits = [p for p in doc.paragraphs if p.text == old]
    if len(hits) != 1:
        raise RuntimeError(f'Expected one exact paragraph, found {len(hits)} for: {old[:80]}')
    p = hits[0]
    style = p.style
    p.text = new
    p.style = style

# MAIN
D = Document(main_in)
repls = {}

repls["Twist suppresses interfacial corrugation in many incommensurate two-dimensional contacts, but a laterally inversion-asymmetric registry landscape can make finite-contact pinning direction dependent. We analyze the published three-shell generalized stacking-fault-energy (GSFE) landscape of 2H Janus MoSSe using an unguided finite contact whose center of mass is free in the full two-dimensional registry plane. Headline depinning thresholds are followed from the lowest-energy zero-force minimum rather than selected from an unconstrained last-surviving-minimum envelope. For the N=127 reference contact at theta=1.5 deg, the prepared rigid branch loses metastability at F_c,+*=3.071135 and F_c,-*=1.258672. Same-spectrum symmetrization removes the global directional bias and exact spatial inversion swaps the thresholds and reverses the deterministic current. Compact hexagonal and disk-like contacts collapse under theta sqrt(N), rotated triangular cuts can reverse the prepared response through registry-state switching, and zero-mean forcing produces cycle-resolved integer lattice-vector transport over all 91 sampled amplitude-period points. Representative plateaus are attracting under independent Floquet checks. Thermal exact-winding identity is fragile, whereas under a stationarity-audited protocol a weaker mean current vector remains statistically nonzero throughout the sampled range to T*=0.70; no thermal extinction scale is inferred. Two in-plane relaxation representations preserve the directional split while renormalizing absolute thresholds. The claims are therefore DFT-anchored reduced-model results, not a parameter-free experimental device prediction."] = \
"Twist suppresses interfacial corrugation in many incommensurate two-dimensional contacts, but a laterally inversion-asymmetric registry landscape can make finite-contact pinning direction dependent. We analyze the published three-shell generalized stacking-fault-energy (GSFE) landscape of 2H Janus MoSSe using an unguided finite contact whose center of mass is free in the full two-dimensional registry plane. Headline depinning thresholds are followed from the lowest-energy zero-force minimum rather than selected from an unconstrained last-surviving-minimum envelope. For the N=127 reference contact at theta=1.5 deg, under the chosen positive/negative-y crystallographic loading axis, the prepared rigid branch loses metastability at F_c,+*=3.071135 and F_c,-*=1.258672. Same-spectrum symmetrization removes the global directional bias and exact spatial inversion swaps the thresholds and reverses the deterministic current. Compact hexagonal and disk-like contacts collapse under theta sqrt(N), rotated triangular cuts can reverse the equilibrium prepared response through registry-state competition, and zero-mean forcing produces cycle-resolved integer lattice-vector transport over all 91 sampled amplitude-period points for the declared m*=1, gamma*=4 dynamical protocol. Representative plateaus are attracting under independent Floquet checks. Thermal exact-winding identity is fragile, whereas under a stationarity-audited protocol a weaker mean current vector remains statistically nonzero throughout the sampled range to T*=0.70; no thermal extinction scale is inferred. Two in-plane relaxation representations preserve the directional split while renormalizing absolute thresholds. The claims are therefore state-, loading-axis-, and protocol-conditioned DFT-anchored reduced-model results, not a parameter-free experimental device prediction."

repls["We separate material symmetry, state preparation, geometry, nonlinear dynamics, stochastic transport, and internal compliance. A translation-minimized diagnostic first tests whether the published GSFE has nonremovable registry inversion asymmetry; registry-origin shifts are then used as a falsification test for coordinate-dependent odd-sector interpretations. Headline static thresholds follow the lowest-energy zero-force minimum under quasi-static positive- and negative-y loading, with competing metastable branches continued separately. Finite-size calculations are extended across compact hexagonal and disk-like families, while rotated triangular boundaries are treated as a competing-registry problem. Deterministic transport is mapped over drive amplitude and period, representative plateaus are tested as attracting relative-periodic orbits, thermal transport is inferred from trajectory-level statistics, and in-plane model-form dependence is tested with both a linear finite-element membrane and a nonlinear bond-angle network. Transverse confinement is retained only as a secondary pathway-control comparison."] = \
"We separate material symmetry, state preparation, geometry, nonlinear dynamics, stochastic transport, and internal compliance. A translation-minimized diagnostic first tests whether the published GSFE has nonremovable registry inversion asymmetry; registry-origin shifts are then used as a falsification test for coordinate-dependent odd-sector interpretations. Headline static thresholds follow the lowest-energy zero-force minimum under quasi-static positive- and negative-y loading, with competing metastable branches continued separately. The chosen y axis is a declared crystallographic loading protocol rather than a rotationally invariant material scalar. Finite-size calculations are extended across compact hexagonal and disk-like families, while rotated triangular boundaries are treated as a competing-registry problem. Deterministic transport is mapped over drive amplitude and period, representative plateaus are tested as attracting relative-periodic orbits, thermal transport is inferred from trajectory-level statistics, and in-plane model-form dependence is tested with both a linear finite-element membrane and a nonlinear bond-angle network. Transverse confinement is retained only as a secondary pathway-control comparison."

repls["Pinned states are full two-dimensional local minima satisfying grad U_N=(0,F_y) with a positive-definite Hessian H. The operational threshold used for all headline claims is branch-followed: at F_y=0 the lowest-energy minimum is identified, and that same minimum is continued quasi-statically under positive or negative force until its stability is lost. Representative 21 x 21 registry-seed enumerations find six stationary points and two stable minima per primitive cell. After an initial 0.25-deg survey, both zero-force minima and their positive/negative loading thresholds were tracked on a 491-point dense/adaptive theta grid from 0 to 3 deg, with 16 independent 21 x 21 stationary-point checkpoints concentrated near the isolated high-order boundary point. Throughout that numerically resolved interval the prepared ground-state family remains lower in zero-force energy and longer lived under both loading directions. This is a numerical interval verification, not an interval-arithmetic proof over every real theta. The older last-stable-minimum-anywhere quantity is retained only as a diagnostic envelope."] = \
"Pinned states are full two-dimensional local minima satisfying grad U_N=(0,F_y) with a positive-definite Hessian H. Here F_y is a spatially uniform center-of-mass/body-force tilt applied at fixed imposed twist; rotational relaxation, applied torque, finite-stiffness spring pulling, and edge- or center-pulling protocols are not included. The operational threshold used for all headline claims is branch-followed: at F_y=0 the lowest-energy minimum is identified, and that same minimum is continued quasi-statically under positive or negative force until its stability is lost. Representative 21 x 21 registry-seed enumerations find six stationary points and two stable minima per primitive cell. After an initial 0.25-deg survey, both zero-force minima and their positive/negative loading thresholds were tracked on a 491-point dense/adaptive theta grid from 0 to 3 deg, with 16 independent 21 x 21 stationary-point checkpoints concentrated near the isolated high-order boundary point. Throughout that numerically resolved interval the prepared ground-state family remains lower in zero-force energy and longer lived under both loading directions. This is a numerical interval verification, not an interval-arithmetic proof over every real theta. The older last-stable-minimum-anywhere quantity is retained only as a diagnostic envelope."

repls["with m*=1 and gamma*=4. The canonical operating point theta=1.5 deg, F0*=2.0 and tau*=40 is supplemented by a 13 x 7 amplitude-period grid: F0*=1.0-4.0 in steps of 0.25 and tau*=20, 30, 40, 50, 60, 70 and 80. Each grid point uses 20 transient and 40 measured cycles with 4000 steps per cycle. The original finite-run classification requires the mean lattice displacement per cycle to lie within 1e-4 of an integer pair (m,n). A stricter cycle-resolved rerun then checks whether every measured cycle repeats the same integer winding. Representative plateaus spanning pinned, low-winding, and high-winding states are tested more strongly by one-period relative-lattice closure, cross-solver Floquet multipliers, time-step refinement, increasing/decreasing amplitude continuation, and position/velocity basin perturbations."] = \
"with m*=1 and gamma*=4. These are reduced dynamical parameters, not values supplied by the GSFE; the mode-locking map is therefore conditional on the declared inertial/damping protocol. The canonical operating point theta=1.5 deg, F0*=2.0 and tau*=40 is supplemented by a 13 x 7 amplitude-period grid: F0*=1.0-4.0 in steps of 0.25 and tau*=20, 30, 40, 50, 60, 70 and 80. Each grid point uses 20 transient and 40 measured cycles with 4000 steps per cycle. The original finite-run classification requires the mean lattice displacement per cycle to lie within 1e-4 of an integer pair (m,n). A stricter cycle-resolved rerun then checks whether every measured cycle repeats the same integer winding. Representative plateaus spanning pinned, low-winding, and high-winding states are tested more strongly by one-period relative-lattice closure, cross-solver Floquet multipliers, time-step refinement, increasing/decreasing amplitude continuation, and position/velocity basin perturbations."

repls["The full-2D directional split survives the stricter prepared-state definition. The N=127 primitive cell contains two stable zero-force minima. On the 491-point dense/adaptive theta grid from 0 to 3 deg, the energy margin U_meta-U_ground, the positive-loading lifetime margin F_c,+^ground-F_c,+^meta, and the negative-loading lifetime margin F_c,-^ground-F_c,-^meta remain positive at every point. Their minimum values occur at the high-twist end and remain 0.17313, 1.70275 and 0.26086, respectively. Sixteen independent 21 x 21 stationary-point checkpoints also recover exactly two stable zero-force minima. At theta=1.5 deg the ground-state thresholds are F_c,+*=3.071135 and F_c,-*=1.258672, whereas the higher-energy minimum loses stability at 0.211059 and 0.611697. The headline split is therefore not produced by selecting different last-surviving metastable basins in the two directions."] = \
"The full-2D directional split survives the stricter prepared-state definition. The N=127 primitive cell contains two stable zero-force minima. On the 491-point dense/adaptive theta grid from 0 to 3 deg, the energy margin U_meta-U_ground, the positive-loading lifetime margin F_c,+^ground-F_c,+^meta, and the negative-loading lifetime margin F_c,-^ground-F_c,-^meta remain positive at every point. Their minimum values occur at the high-twist end and remain 0.17313, 1.70275 and 0.26086, respectively. Sixteen independent 21 x 21 stationary-point checkpoints also recover exactly two stable zero-force minima. At theta=1.5 deg the ground-state thresholds are F_c,+*=3.071135 and F_c,-*=1.258672, giving Delta F_c=+1.812463, whereas the higher-energy minimum loses stability at 0.211059 and 0.611697, giving Delta F_c=-0.400638. Thus the same GSFE supports opposite directional signs for the two prepared zero-force basins; the headline rectification is explicitly ground-state-preparation conditioned rather than basin independent."

repls["For the ground-state family, the positive- and negative-y thresholds are 3.485120 and 1.422236 at zero twist, 3.071135 and 1.258672 at theta=1.5 deg, and 1.883315 and 0.782412 at theta=3 deg. Over 0-3 deg the normalized split has mean rho=0.417894, sample SD 0.002279 and range 0.412984-0.420366. The branch-followed thresholds therefore retain the near-common geometric envelope found in the unguided reanalysis. The k_perp*=25 reference gives a much smaller rho=0.102977 at theta=1.5 deg; confinement reorganizes the escape pathway rather than creating the free-contact directionality."] = \
"For the ground-state family, the positive- and negative-y thresholds are 3.485120 and 1.422236 at zero twist, 3.071135 and 1.258672 at theta=1.5 deg, and 1.883315 and 0.782412 at theta=3 deg. Over 0-3 deg the normalized split has mean rho=0.417894, sample SD 0.002279 and range 0.412984-0.420366. A separate in-plane force-direction scan at theta=1.5 deg shows that the signed split is strongly axis dependent: |rho| is about 1.63e-4 on a symmetry-axis orientation and reaches about 0.4186 on the tested strong-rectification orientation. The headline positive/negative-y comparison is therefore one chosen crystallographic loading axis, not a rotationally invariant friction scalar. The branch-followed thresholds retain the near-common geometric envelope found in the unguided reanalysis along that declared axis. The k_perp*=25 reference gives a much smaller rho=0.102977 at theta=1.5 deg; confinement reorganizes the escape pathway rather than creating the free-contact directionality."

repls["The high-twist boundary reversal has a more specific mechanism than the earlier global-envelope description. For the 20 and 25 deg triangular cuts, two low-energy registry minima coexist and carry opposite branch-followed directional biases. As twist increases their zero-force energies cross, changing which registry is the prepared ground state. The ground-state switches occur at theta=2.92127801 deg for the 20 deg cut and 2.84723312 deg for the 25 deg cut. Immediately across each crossing the prepared-state Delta F_c changes from about +0.67/+0.70 to about -0.67/-0.70. Thus the physically relevant reversal is a registry-state switch rather than a smooth zero crossing of a global last-surviving-minimum envelope."] = \
"The high-twist boundary reversal has a more specific mechanism than the earlier global-envelope description. For the 20 and 25 deg triangular cuts, two low-energy registry minima coexist and carry opposite branch-followed directional biases. As twist increases their zero-force energies cross, changing which registry is selected as the prepared ground state when the contact is re-prepared independently at each fixed twist. The ground-state crossings occur at theta=2.92127801 deg for the 20 deg cut and 2.84723312 deg for the 25 deg cut. Immediately across each crossing the prepared-state Delta F_c changes from about +0.67/+0.70 to about -0.67/-0.70. This is an equilibrium family-selection result under fixed-twist re-preparation. No A-to-B transition path, activation barrier, continuous twist-sweep switching protocol, or hysteresis was calculated, so the result is not a kinetic switching prediction."

repls["The term 'intrinsic' remains deliberately narrow. It means only that no transverse guiding potential is required to obtain rectification in the baseline finite-contact GSFE model. The headline model is rigid, and the two extensions introduced here add in-plane compliance only; neither is a fully three-dimensional atomistic slider. Inertia, damping, load response and experimental state preparation are also not supplied by the same first-principles calculation. Engineered confinement is therefore best viewed as pathway control applied to an already rectifying reduced system."] = \
"The term 'intrinsic' remains deliberately narrow. It means only that no transverse guiding potential is required to obtain rectification in the baseline finite-contact GSFE model. It does not mean preparation independent, loading-axis independent, damping independent, or mechanically protocol independent: the competing metastable basin at theta=1.5 deg carries the opposite signed static split, the force-direction scan is strongly anisotropic, and the dynamical map is conditioned on declared reduced inertial/damping parameters. The headline model is rigid, and the two extensions introduced here add in-plane compliance only; neither is a fully three-dimensional atomistic slider. Inertia, damping, load response and experimental state preparation are also not supplied by the same first-principles calculation. Engineered confinement is therefore best viewed as pathway control applied to an already rectifying reduced system."

repls["The theta sqrt(N) similarity is substantially more robust than in the initial ten-size calculation. Larger hexagons and an independent disk-like compact family remain collapsed to about 0.1% or better across a dense Theta=0-20 grid, supporting the structure-factor interpretation for compact rigid contacts. This result sits alongside established shape- and edge-controlled finite-contact scaling [5,7] and very recent moire-boundary/edge-energy theories [25,26]; the novelty claim is therefore not the generic existence of edge-controlled scaling or an inverse-linear-size angle. Boundary orientation behaves differently in the present model: sufficiently rotated triangular cuts bring two registry minima into competition; their zero-force energy crossing changes the prepared ground state and reverses its branch-followed directional bias. The A/B competition and crossing persist across the tested surrogate outer-site weights, but the switch angle - and whether it falls inside the nominal 0-3 deg interval - is edge-model dependent. The qualitative registry competition is therefore a reduced-model prediction, whereas the numerical reversal angle is not a universal material constant."] = \
"The theta sqrt(N) similarity is substantially more robust than in the initial ten-size calculation. Larger hexagons and an independent disk-like compact family remain collapsed to about 0.1% or better across a dense Theta=0-20 grid, supporting the structure-factor interpretation for compact rigid contacts. This result sits alongside established shape- and edge-controlled finite-contact scaling [5,7] and very recent moire-boundary/edge-energy theories [25,26]; the novelty claim is therefore not the generic existence of edge-controlled scaling or an inverse-linear-size angle. Boundary orientation behaves differently in the present model: sufficiently rotated triangular cuts bring two registry minima into competition; their zero-force energy crossing changes the equilibrium prepared ground state and reverses its branch-followed directional bias under fixed-twist re-preparation. The A/B competition and crossing persist across the tested surrogate outer-site weights, but the switch angle - and whether it falls inside the nominal 0-3 deg interval - is edge-model dependent. Because no transition barrier or twist-sweep hysteresis was calculated, the qualitative registry competition is an equilibrium reduced-model prediction rather than a demonstrated kinetic switching event, and the numerical reversal angle is not a universal material constant."

repls["A static threshold inequality does not by itself determine a rocking-ratchet phase diagram. Generic rectification and phase locking on periodic substrates are established [19,20,23,24]; the material-specific question here is whether the same finite MoSSe contact that exhibits prepared-state directional depinning supports lattice-vector relative-periodic transport under zero-mean longitudinal forcing. The 91-point F0-tau scan is stronger than a mean-displacement classification because every sampled state repeats one winding cycle-by-cycle after transients, and representative plateaus spanning several windings are independently verified as attracting relative-periodic states. Thermal trajectories separate exact mode identity from stationary directed transport. After explicit burn-in, block-stationarity, initial-state-memory, independent-seed and timestep checks, the deterministic target winding is already strongly mixed while a smaller mean drift remains statistically nonzero throughout the sampled range to T*=0.70. The negative-v cycle fraction approaches one-half as temperature rises, showing that a weak bias can survive even when individual cycles are nearly balanced and exact mode identity is rare. The earlier 0.60/0.65/0.70 detectability boundaries obtained from short observation windows are therefore retired. No universal thermal critical temperature or complete operating diagram is inferred outside the tested drive, damping and reduced-temperature ranges."] = \
"A static threshold inequality does not by itself determine a rocking-ratchet phase diagram. Generic rectification and phase locking on periodic substrates are established [19,20,23,24]; the material-specific question here is whether the same finite MoSSe contact that exhibits prepared-state directional depinning supports lattice-vector relative-periodic transport under zero-mean longitudinal forcing. The 91-point F0-tau scan is stronger than a mean-displacement classification because every sampled state repeats one winding cycle-by-cycle after transients, and representative plateaus spanning several windings are independently verified as attracting relative-periodic states. The map is nevertheless protocol specific. At fixed theta=1.5 deg, F0*=2.0 and tau*=40, a targeted damping sweep gives windings (1,-10), (1,-3) and (2,-2) at gamma*=1, 2 and 3, retains (1,-1) for gamma*=4-6, and becomes pinned (0,0) for gamma*=8-10. The sampled vector-locking map is therefore a property of the declared m*=1, gamma*=4 reduced dynamical protocol, not a material-only MoSSe phase diagram. Thermal trajectories separate exact mode identity from stationary directed transport. After explicit burn-in, block-stationarity, initial-state-memory, independent-seed and timestep checks, the deterministic target winding is already strongly mixed while a smaller mean drift remains statistically nonzero throughout the sampled range to T*=0.70. The negative-v cycle fraction approaches one-half as temperature rises, showing that a weak bias can survive even when individual cycles are nearly balanced and exact mode identity is rare. No universal thermal critical temperature or complete operating diagram is inferred outside the tested drive, damping and reduced-temperature ranges."

repls["Three model-input limitations remain central. First, the source DFT GSFE relaxes the interlayer separation independently at each aligned registry [12], but the finite-contact model still represents the interface as a sitewise local-registry sum. Collective out-of-plane corrugation or buckling, atomistic edge reconstruction and chemistry, defects, and nonlocal edge energetics are absent. The in-plane calculations show why a higher model level matters: absolute thresholds shift with compliance even when the directional ratio survives. A public empirical SW plus registry-dependent interlayer candidate is therefore retained only as a qualitative stress test because it fails the published higher-harmonic GSFE contract. Recent dispersion-aware machine-learning potentials for multilayer TMDs provide a plausible route toward higher-level relaxation [21], but a Janus-specific 2H MoSSe GSFE contract must be passed before such a model is used as quantitative validation. Second, load-dependent registry energetics, dissipation, participating mass, and laboratory state preparation are not supplied by the present GSFE; reduced temperature and time must not be converted into kelvin or physical frequency without independent calibration. Third, physical polarity reversal is not represented by eta scaling or the matched mathematical inversion control. Beyond these material-input limitations, the isolated higher-order stability point near theta=2.9734 deg merits a dedicated two-parameter normal-form study, and the continuous amplitude-period phase diagram may contain unsampled multistability or bifurcation structure."] = \
"Three model-input limitations remain central. First, the source DFT GSFE relaxes the interlayer separation independently at each aligned registry [12], but the finite-contact model still represents the interface as a sitewise local-registry sum. Collective out-of-plane corrugation or buckling, atomistic edge reconstruction and chemistry, defects, and nonlocal edge energetics are absent. The in-plane calculations show why a higher model level matters: absolute thresholds shift with compliance even when the directional ratio survives. A public empirical SW plus registry-dependent interlayer candidate is therefore retained only as a qualitative stress test because it fails the published higher-harmonic GSFE contract. Recent dispersion-aware machine-learning potentials for multilayer TMDs provide a plausible route toward higher-level relaxation [21], but a Janus-specific 2H MoSSe GSFE contract must be passed before such a model is used as quantitative validation. Second, the present thresholds and driven trajectories are defined at fixed imposed twist under a spatially uniform center-of-mass/body-force protocol. Rotational relaxation or applied torque, finite-stiffness spring pulling, edge or center pulling, and the associated load-localization physics are not modeled. Load-dependent registry energetics, dissipative calibration, participating mass, and laboratory state preparation are likewise not supplied by the present GSFE; reduced temperature and time must not be converted into kelvin or physical frequency without independent calibration. Third, physical polarity reversal is not represented by eta scaling or the matched mathematical inversion control. Beyond these material-input limitations, the isolated higher-order stability point near theta=2.9734 deg merits a dedicated two-parameter normal-form study, and the continuous amplitude-period phase diagram may contain unsampled multistability or bifurcation structure."

repls["A finite contact constructed from the published 2H Janus MoSSe GSFE exhibits branch-followed full two-dimensional mechanical rectification without an added transverse guide. At theta=1.5 deg the prepared N=127 rigid thresholds are F_c,+*=3.071135 and F_c,-*=1.258672, and dense/adaptive continuation over 0-3 deg finds no exchange between the prepared ground family and the competing metastable family. Translation-minimized asymmetry diagnostics and matched same-2H controls identify registry-space inversion asymmetry as the causal conservative ingredient within the reduced model. Compact-contact thresholds obey theta sqrt(N) similarity with finite-size corrections toward the inverse-linear-size law, while rotated triangular boundaries can reverse the prepared bias through a ground-state registry switch whose angle is edge-model dependent. Zero-mean forcing generates cycle-resolved integer lattice-vector transport over all 91 sampled amplitude-period points, with representative plateaus independently verified as attracting. Thermal exact-winding identity is fragile, but after stationarity and replication checks a weaker mean vector drift remains statistically nonzero through the largest sampled T*=0.70; no extinction temperature is established. Linear FEM and independently reconstructed nonlinear VFF relaxations soften absolute thresholds while preserving the directional split. The resulting evidence supports a self-consistent DFT-anchored reduced-model mechanism; it does not establish a unique experimental friction coefficient, a physical polarity law, full 3D atomistic relaxation, a Kelvin-scale thermal boundary or a universal nonlinear phase diagram."] = \
"For the lowest-energy zero-force preparation, fixed imposed twist, and the chosen positive/negative-y center-of-mass loading axis, a finite contact constructed from the published 2H Janus MoSSe GSFE exhibits branch-followed full two-dimensional mechanical rectification without an added transverse guide. At theta=1.5 deg the prepared N=127 rigid thresholds are F_c,+*=3.071135 and F_c,-*=1.258672; the competing metastable basin carries the opposite signed split, so the response is explicitly state conditioned. Translation-minimized asymmetry diagnostics and matched same-2H controls identify registry-space inversion asymmetry as the causal conservative ingredient within the reduced model. Compact-contact thresholds obey theta sqrt(N) similarity with finite-size corrections toward the inverse-linear-size law, while rotated triangular boundaries can reverse the equilibrium prepared bias through an edge-sensitive registry energy crossing under fixed-twist re-preparation; kinetic twist-sweep switching or hysteresis is not established. Under the declared m*=1, gamma*=4 protocol, zero-mean forcing generates cycle-resolved integer lattice-vector transport over all 91 sampled amplitude-period points, with representative plateaus independently verified as attracting. Thermal exact-winding identity is fragile, but after stationarity and replication checks a weaker mean vector drift remains statistically nonzero through the largest sampled T*=0.70; no extinction temperature is established. Linear FEM and independently reconstructed nonlinear VFF relaxations soften absolute thresholds while preserving the directional split. The resulting evidence supports a self-consistent DFT-anchored reduced-model mechanism; it does not establish loading-axis or damping invariance, a unique experimental friction coefficient, a physical polarity law, full 3D atomistic relaxation, a Kelvin-scale thermal boundary, or a universal nonlinear phase diagram."

for old,new in repls.items():
    replace_exact(D, old, new)
D.save(main_out)

# SI
S = Document(si_in)
si_repls = {}
si_repls["The edge-weight test is intentionally not an atomistic edge-relaxation model. Across all ten tested cut/weight combinations the A/B energy crossing persists, both candidate registries are stable zero-force minima at the crossing, and the two families retain opposite directional biases. What is not robust is the numerical switch angle or its placement inside a chosen finite twist window: for example, at weight 0.5 the 20 and 25 deg crossings move to 3.1701 and 3.0832 deg, outside the nominal 0-3 deg interval. The reduced-model claim is therefore competing-registry switching with edge-sensitive location, not a universal reversal twist."] = \
"The edge-weight test is intentionally not an atomistic edge-relaxation model. Across all ten tested cut/weight combinations the A/B energy crossing persists, both candidate registries are stable zero-force minima at the crossing, and the two families retain opposite directional biases. What is not robust is the numerical switch angle or its placement inside a chosen finite twist window: for example, at weight 0.5 the 20 and 25 deg crossings move to 3.1701 and 3.0832 deg, outside the nominal 0-3 deg interval. The crossing is an equilibrium family-selection result obtained by re-preparing the lower-energy zero-force state at each fixed twist; no A-to-B transition barrier, continuous twist sweep, or hysteresis was calculated. The reduced-model claim is therefore competing-registry switching with edge-sensitive equilibrium location, not a universal kinetic reversal twist."

si_repls["The canonical (1,-1) leading multiplier agrees across explicit high-order and implicit stiff solvers, so only rho_F<1 is interpreted physically. The same test was extended to five additional plateau representatives. Using the tighter DOP853 solve, the leading spectral radii are approximately 1.39e-31 for (0,0), 4.62e-24 for (1,-1) at F0*=1.9625, 5.69e-20 for (1,-2), 9.47e-17 for (2,-3), 5.21e-13 for (3,-4), and 1.62e-15 for the high-winding (2,-7) state at tau*=70; Radau confirms rho_F<1 in every case. Across these six states, 24/24 time-step tests and 162/162 local basin perturbations recover the expected winding. Increasing and decreasing amplitude continuation at tau*=40 agree at all 61 sampled amplitudes. These checks establish representative local attraction, not global attractor uniqueness."] = \
"The canonical (1,-1) leading multiplier agrees across explicit high-order and implicit stiff solvers, so only rho_F<1 is interpreted physically. The same test was extended to five additional plateau representatives. Using the tighter DOP853 solve, the leading spectral radii are approximately 1.39e-31 for (0,0), 4.62e-24 for (1,-1) at F0*=1.9625, 5.69e-20 for (1,-2), 9.47e-17 for (2,-3), 5.21e-13 for (3,-4), and 1.62e-15 for the high-winding (2,-7) state at tau*=70; Radau confirms rho_F<1 in every case. Across these six states, 24/24 time-step tests and 162/162 local basin perturbations recover the expected winding. Increasing and decreasing amplitude continuation at tau*=40 agree at all 61 sampled amplitudes. A targeted damping sweep at theta=1.5 deg, F0*=2.0 and tau*=40 changes the asymptotic winding from (1,-10), (1,-3) and (2,-2) at gamma*=1, 2 and 3 to (1,-1) for gamma*=4-6 and (0,0) for gamma*=8-10. The sampled mode-locking map is therefore conditional on the declared m*=1, gamma*=4 protocol. These checks establish representative local attraction, not global attractor uniqueness or damping-independent material dynamics."

si_repls["Each trajectory contains 60 burn cycles and 100 measured cycles at dt=0.02. The full T*=0.02-0.70 series uses N=500 independent trajectories per temperature, and the high-temperature band T*=0.50-0.70 is repeated with a second independent N=500 ensemble. The trajectory is the inferential unit. Late 20-cycle blocks show no resolved two-component drift in either high-temperature seed ensemble, and deterministic-orbit, zero-force ground-state and competing-metastable starts become identical to numerical precision by cycle 38 at the latest under common noise. The pooled high-temperature mean vector decreases from (0.08001,-0.15509) at T*=0.50 to (0.03700,-0.07645) at T*=0.70, but a 50,000-resample trajectory bootstrap still excludes the zero vector at every sampled high-temperature point. At T*=0.70 the component intervals are u in [0.01265,0.06132] and v in [-0.10088,-0.05195]. P(v_cycle<0) approaches one-half but remains slightly above it through 0.70, while the exact target-winding probability is only about 1.1-1.6% over T*=0.50-0.70. The earlier 10-burn + 10-measure pilot boundaries shift with observation length and are therefore retired rather than interpreted as physical thermal thresholds. Targeted dt=0.04, 0.02 and 0.01 reruns at T*=0.60, 0.65 and 0.70 agree within 1.12 combined standard errors in either mean-current component."] = \
"Each trajectory contains 60 burn cycles and 100 measured cycles at dt=0.02. The full T*=0.02-0.70 series uses N=500 independent trajectories per temperature, and the high-temperature band T*=0.50-0.70 is repeated with a second independent N=500 ensemble. The trajectory is the inferential unit. Late 20-cycle blocks show no resolved two-component drift in either high-temperature seed ensemble, and deterministic-orbit, zero-force ground-state and competing-metastable starts become identical to numerical precision by cycle 38 at the latest under common noise. The pooled high-temperature mean vector decreases from (0.08001,-0.15509) at T*=0.50 to (0.03700,-0.07645) at T*=0.70, but a 50,000-resample trajectory bootstrap still excludes the zero vector at every sampled high-temperature point. At T*=0.70 the component intervals are u in [0.01265,0.06132] and v in [-0.10088,-0.05195]. P(v_cycle<0) approaches one-half but remains slightly above it through 0.70, while the exact target-winding probability is only about 1.1-1.6% over T*=0.50-0.70. Targeted dt=0.04, 0.02 and 0.01 reruns at T*=0.60, 0.65 and 0.70 agree within 1.12 combined standard errors in either mean-current component."

si_repls["The audit resolves the computational ambiguities that can be decided with the published GSFE and shows that the headline directional split survives two in-plane compliance representations. Remaining inputs are a Janus-specific full-three-dimensional atomistic potential that passes the published 2H GSFE contract; collective finite-flake corrugation/buckling and edge reconstruction; load-dependent stacking energetics; polarity-resolved first-principles surfaces; dissipative and inertial calibration; laboratory state preparation; and experiment. The exact triangular switch angle is especially edge-model sensitive, and reduced temperature or period must not be converted into kelvin or physical frequency without independent calibration."] = \
"The audit resolves the computational ambiguities that can be decided with the published GSFE and shows that the headline directional split survives two in-plane compliance representations. Remaining inputs are a Janus-specific full-three-dimensional atomistic potential that passes the published 2H GSFE contract; collective finite-flake corrugation/buckling and edge reconstruction; load-dependent stacking energetics; polarity-resolved first-principles surfaces; dissipative and inertial calibration; laboratory state preparation; and experiment. The present mechanics keep twist externally fixed and use a spatially uniform center-of-mass/body-force protocol; rotational relaxation or torque, finite-stiffness spring pulling, edge/center pulling, and corresponding stress localization are not represented. The exact triangular switch angle is especially edge-model sensitive, and reduced temperature or period must not be converted into kelvin or physical frequency without independent calibration."

for old,new in si_repls.items():
    replace_exact(S, old, new)
S.save(si_out)
print(main_out)
print(si_out)
